//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_TheServices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gen_TheServices()
        {
            this.Gen_Machines = new HashSet<Gen_Machines>();
            this.Gen_ServiceRates = new HashSet<Gen_ServiceRates>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Service_Type { get; set; }
        public string Service_Name { get; set; }
        public Nullable<int> Service_RateCharge { get; set; }
        public Nullable<int> Machine_Device { get; set; }
        public string Max_Range { get; set; }
        public Nullable<decimal> Max_Charges { get; set; }
        public Nullable<decimal> Min_Charges { get; set; }
        public Nullable<decimal> Field1 { get; set; }
        public Nullable<decimal> Field2 { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<System.DateTime> RecordTimeStamp { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Machines> Gen_Machines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_ServiceRates> Gen_ServiceRates { get; set; }
        public virtual Gen_ServiceType Gen_ServiceType { get; set; }
    }
}
