//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMB_ProductionEntities : DbContext
    {
        public EMB_ProductionEntities()
            : base("name=EMB_ProductionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gen_Brands> Gen_Brands { get; set; }
        public virtual DbSet<Gen_Categories> Gen_Categories { get; set; }
        public virtual DbSet<Gen_Components> Gen_Components { get; set; }
        public virtual DbSet<Gen_JobOrders> Gen_JobOrders { get; set; }
        public virtual DbSet<Gen_MachineParameters> Gen_MachineParameters { get; set; }
        public virtual DbSet<Gen_Machines> Gen_Machines { get; set; }
        public virtual DbSet<Gen_Products> Gen_Products { get; set; }
        public virtual DbSet<Gen_ServiceRates> Gen_ServiceRates { get; set; }
        public virtual DbSet<Gen_ServiceType> Gen_ServiceType { get; set; }
        public virtual DbSet<Gen_Stock> Gen_Stock { get; set; }
        public virtual DbSet<Gen_TheServices> Gen_TheServices { get; set; }
        public virtual DbSet<Gen_ThreadUsage> Gen_ThreadUsage { get; set; }
        public virtual DbSet<GenDesign> GenDesigns { get; set; }
        public virtual DbSet<Hr_Customers> Hr_Customers { get; set; }
    }
}
