//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_MachineParameters
    {
        public int Id { get; set; }
        public string HeadToHead { get; set; }
        public Nullable<decimal> FrameHeight { get; set; }
        public bool Deleted { get; set; }
        public bool Active { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
