//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_Designs
    {
        public int Id { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public string EntryType { get; set; }
        public string Fabric { get; set; }
        public string Remarks { get; set; }
        public string Extra_Service { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<int> DNo { get; set; }
        public Nullable<int> Head_Email { get; set; }
        public Nullable<int> Req_Repeats { get; set; }
        public Nullable<int> Head { get; set; }
        public Nullable<int> Stitches { get; set; }
        public Nullable<int> Seq { get; set; }
        public Nullable<int> W_Head { get; set; }
        public Nullable<int> Colors { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Component_Code { get; set; }
        public Nullable<int> DCode { get; set; }
        public string CollectionName { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool? Status { get; set; }
        public string Seq_Id { get; set; }
        public string Seq_Usage { get; set; } 
        public string T_Id { get; set; }
        public string T_Usage { get; set; }
        public string MD_Id { get; set; }
    }
}
