//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_Brands
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gen_Brands()
        {
            this.Gen_Machines = new HashSet<Gen_Machines>();
            this.Gen_Categories = new HashSet<Gen_Categories>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string BrandName { get; set; }
        public string Description { get; set; }
        public int BranchId { get; set; }
        public bool Deleted { get; set; }
        public bool Active { get; set; }
        public System.DateTime RecordTimeStamp { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Machines> Gen_Machines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Categories> Gen_Categories { get; set; }
        public virtual Gen_Brands Gen_Brands1 { get; set; }
        public virtual Gen_Brands Gen_Brands2 { get; set; }
    }
}
