//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_Components
    {
        public int Id { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<int> D_Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> HeadToHead { get; set; }
        public Nullable<int> Stitch { get; set; }
        public Nullable<int> Tilla { get; set; }
        public Nullable<int> Seq_A { get; set; }
        public Nullable<int> Seq_B { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
