//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gen_Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gen_Products()
        {
            this.Gen_Stock = new HashSet<Gen_Stock>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CatId { get; set; }
        public string Prod_Name { get; set; }
        public string Prod_Code { get; set; }
        public string Prod_Description { get; set; }
        public string Prod_Qty { get; set; }
        public string Prod_Length { get; set; }
        public string Prod_Weight { get; set; }
        public Nullable<System.DateTime> Prod_DateIn { get; set; }
        public Nullable<System.DateTime> Prod_DateOut { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int BranchId { get; set; }
        public bool Deleted { get; set; }
        public bool Active { get; set; }
        public System.DateTime RecordTimeStamp { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Category_Name { get; set; }
        public string Brand_Name { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public string Price_Method { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gen_Stock> Gen_Stock { get; set; }
    }
}
